#docker run --rm -d --name cassandra --hostname cassandra --network cassandra cassandra
#docker run --rm --network cassandra -v "$(pwd)/data.cql:/scripts/data.cql" -e CQLSH_HOST=cassandra -e CQLSH_PORT=9042 -e CQLVERSION=3.4.5 nuvo/docker-cqlsh

services:
  cassandra:
    image:  cassandra:latest
    ports: 
      - "9042:9042"
    environment:
      - CASSANDRA_DC=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
networks:
  cassandra:
    driver: bridge
    

    




